name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py-version: [3.7, 3.8, 3.9]
        excludes:
          - py-version: 3.9
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python version ${{ matrix.py-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}